name: Actions
on: workflow_dispatch
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/issue
        id: test
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Some title
          body: Some body
          assignees: |
            OndrejTuma
      - run: echo ${{ steps.outputs.issue }}
