name: Set Env

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Environment
        options:
          - Development
          - QA
          - UAT
          - Production

jobs:
  set:
    runs-on: ubuntu-latest
    steps:
      - run: echo "inputs ${{ fromJson(inputs) }}"
      - run: echo "env var ${{ env.TARGET_ENVIRONMET }} and input ${{ inputs.environment }}"
        env:
          TARGET_ENVIRONMET: >
            ${{ fromJson('{
              "Development": "dev",
              "Production": "prod"
            }')[inputs.environment] }}
