name: Test

on: pull_request

env:
  PATHH: code-coverage

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Merge coverage files
        run: |
          ls -l
          echo "$PATHH"
          mkdir merged-coverage
