name: Trigger reusable workflow

on: push

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: test/reusable-wf
          path: wf-path
      - uses: ./wf-path/.github/actions/reusable