name: Upload artifact and get a list

on: push

jobs:
  doit:
    runs-on: ubuntu-latest
    steps:
      - name: Create some file to upload
        run: echo "test" > test.txt

      - name: Store artifact's name
        id: artifact-name
        env:
          REF: ${{ github.ref }}
        run: echo "::set-output name=value::${REF////-}-test"

      - name: List, filter and delete artifacts
        uses: actions/github-script@v4
        id: artifact
        with:
          script: |
            const { owner, repo } = context.issue
            
            const res = await github.actions.listArtifactsForRepo({
              owner,
              repo,
            })
            
            res.data.artifacts
              .filter(({ name }) => name === '${{ steps.artifact-name.outputs.value }}')
              .forEach(({ id }) => {
                github.actions.deleteArtifact({
                  owner,
                  repo,
                  artifact_id: id,
                })
              })

      - name: Upload latest artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.artifact-name.outputs.value }}
          path: test.txt